### ISSUE TITLE
Double entry in Bolt extensions 'store'

### ISSUE THREAD

**Issue by evertalbers** [dactivo/Bolt.cm-HTML-minifier#1]
This extension shows up twice in e.g. http://extensions.bolt.cm/browse?q=minif&type=

Would it be possible to clean up one of the 2 entries?

**Comment by dactivo** [comment]
I can't find the option to delete it when I login. I would like to get rid of the one called:
"Bolt HTML Minifier - Minify your HTML output"

**Comment by evertalbers** [comment]
I'll ask in the Bolt IRC forum (and hope that I won't miss the reply - busy day)

**Comment by GwendolenLynch** [comment]
Done!

**Comment by dactivo** [comment]
Thx!
